<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            ['id' => 1, 'division_id' => 1, 'last_name' => 'JIMENEZ', 'first_name' => 'PINKY', 'middle_name' => 'TUMALIUAN', 'suffix' => null, 'position' => 'DIRECTOR IV', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:22:34', 'updated_at' => '2025-09-30 19:22:34'],
            ['id' => 2, 'division_id' => 1, 'last_name' => 'TUMALIUAN', 'first_name' => 'MARK JOHN', 'middle_name' => 'CUDIAMAT', 'suffix' => null, 'position' => 'Admin Aide IV/Driver II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:25:48', 'updated_at' => '2025-09-30 19:25:48'],
            ['id' => 3, 'division_id' => 1, 'last_name' => 'DAWIDEO', 'first_name' => 'SAMANTHA', 'middle_name' => 'PAYUKET', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:27:44', 'updated_at' => '2025-09-30 19:27:44'],
            ['id' => 4, 'division_id' => 2, 'last_name' => 'VILLAFUERTE', 'first_name' => 'MINA FLOR', 'middle_name' => 'TALAY', 'suffix' => null, 'position' => 'CAO', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:28:25', 'updated_at' => '2025-09-30 19:28:25'],
            ['id' => 5, 'division_id' => 2, 'last_name' => 'DEL ROSARIO', 'first_name' => 'JEMAR JAY', 'middle_name' => 'CALAYAN', 'suffix' => null, 'position' => 'Accountant III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:29:00', 'updated_at' => '2025-09-30 20:38:57'],
            ['id' => 6, 'division_id' => 2, 'last_name' => 'ABRIGO', 'first_name' => 'LOT-LOT', 'middle_name' => 'ACERA', 'suffix' => null, 'position' => 'Budget Officer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:29:42', 'updated_at' => '2025-09-30 19:29:42'],
            ['id' => 7, 'division_id' => 2, 'last_name' => 'AMMASI', 'first_name' => 'JAYFER', 'middle_name' => 'TABAO-ICAN', 'suffix' => null, 'position' => 'HRMO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:30:41', 'updated_at' => '2025-09-30 19:30:41'],
            ['id' => 8, 'division_id' => 2, 'last_name' => 'BUENO', 'first_name' => 'CHRISTINE JOYCE', 'middle_name' => 'VILLALUZ', 'suffix' => null, 'position' => 'Cashier II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:39:24', 'updated_at' => '2025-09-30 19:39:24'],
            ['id' => 9, 'division_id' => 2, 'last_name' => 'MANUEL', 'first_name' => 'EDWARD', 'middle_name' => 'CABUTAJE', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:40:21', 'updated_at' => '2025-09-30 19:40:21'],
            ['id' => 10, 'division_id' => 2, 'last_name' => 'MANUEL', 'first_name' => 'EDMUND', 'middle_name' => 'CABUTAJE', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:41:08', 'updated_at' => '2025-09-30 19:41:08'],
            ['id' => 11, 'division_id' => 2, 'last_name' => 'DOMINGO', 'first_name' => 'ELON', 'middle_name' => 'FLORES', 'suffix' => null, 'position' => 'CEO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:41:40', 'updated_at' => '2025-09-30 19:41:40'],
            ['id' => 12, 'division_id' => 2, 'last_name' => 'MAGGAY', 'first_name' => 'CLARO', 'middle_name' => 'MATAMMU', 'suffix' => null, 'position' => 'ECET I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:42:12', 'updated_at' => '2025-09-30 19:42:12'],
            ['id' => 13, 'division_id' => 2, 'last_name' => 'FUGABAN', 'first_name' => 'PABLO', 'middle_name' => 'GERALDO', 'suffix' => null, 'position' => 'Admin Aide IV/Driver', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:42:47', 'updated_at' => '2025-09-30 19:42:47'],
            ['id' => 14, 'division_id' => 2, 'last_name' => 'TUMALIUAN', 'first_name' => 'NODEL', 'middle_name' => 'MEMAN', 'suffix' => null, 'position' => 'Admin Aide IV./Driver II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:43:20', 'updated_at' => '2025-09-30 19:43:20'],
            ['id' => 15, 'division_id' => 2, 'last_name' => 'CALAYAN', 'first_name' => 'KIMBERLY ANN', 'middle_name' => 'BANATAO', 'suffix' => null, 'position' => 'Admin Officer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:43:54', 'updated_at' => '2025-09-30 19:43:54'],
            ['id' => 16, 'division_id' => 2, 'last_name' => 'BAQUIRAN', 'first_name' => 'JULIUS CEZAR', 'middle_name' => 'CALIGUIRAN', 'suffix' => null, 'position' => 'Admin Officer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:44:23', 'updated_at' => '2025-09-30 19:44:23'],
            ['id' => 17, 'division_id' => 2, 'last_name' => 'BAQUIRAN', 'first_name' => 'MAR ELVISON', 'middle_name' => 'ANGOBONG', 'suffix' => null, 'position' => 'Admin Officer II (HRMO)', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:45:23', 'updated_at' => '2025-09-30 19:45:23'],
            ['id' => 18, 'division_id' => 2, 'last_name' => 'PRUDENCIADO', 'first_name' => 'JENNY', 'middle_name' => 'SALA', 'suffix' => null, 'position' => 'Budget Officer', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:45:54', 'updated_at' => '2025-09-30 19:45:54'],
            ['id' => 19, 'division_id' => 2, 'last_name' => 'ARGONZA', 'first_name' => 'EDWARD MARK', 'middle_name' => 'DELOS SANTOS', 'suffix' => null, 'position' => 'Admin Officer I (Supply Officer I)', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:46:26', 'updated_at' => '2025-09-30 19:46:26'],
            ['id' => 20, 'division_id' => 2, 'last_name' => 'TABUG', 'first_name' => 'SHEREEN', 'middle_name' => 'JUNGCO', 'suffix' => null, 'position' => 'Admin Officer I (Records Officer I)', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:46:56', 'updated_at' => '2025-09-30 19:46:56'],
            ['id' => 21, 'division_id' => 2, 'last_name' => 'TUMALIUAN', 'first_name' => 'LEONOR', 'middle_name' => 'JUANDAY', 'suffix' => null, 'position' => 'Admin Officer I (Cashier I)', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:47:22', 'updated_at' => '2025-09-30 19:47:22'],
            ['id' => 22, 'division_id' => 2, 'last_name' => 'MONTES', 'first_name' => 'MARIZA NOVA', 'middle_name' => 'MIRANDA', 'suffix' => null, 'position' => 'Admin Asst II (Acctg Clerk)', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:47:57', 'updated_at' => '2025-09-30 19:47:57'],
            ['id' => 23, 'division_id' => 2, 'last_name' => 'SANTOS', 'first_name' => 'IVAN PAUL', 'middle_name' => 'MATIAS', 'suffix' => null, 'position' => 'Admin Aide IV', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:48:24', 'updated_at' => '2025-09-30 19:48:24'],
            ['id' => 24, 'division_id' => 3, 'last_name' => 'GOMEZ', 'first_name' => 'MAGDALENA', 'middle_name' => 'DACUYCUY', 'suffix' => null, 'position' => 'ITO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:49:00', 'updated_at' => '2025-09-30 19:49:00'],
            ['id' => 25, 'division_id' => 3, 'last_name' => 'BATANG', 'first_name' => 'JOHNY', 'middle_name' => 'CALAYAN', 'suffix' => null, 'position' => 'ENGR III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:49:29', 'updated_at' => '2025-09-30 19:49:29'],
            ['id' => 26, 'division_id' => 3, 'last_name' => 'ELCHICO', 'first_name' => 'JOEY MARK', 'middle_name' => 'DE GUZMAN', 'suffix' => null, 'position' => 'ITO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:50:01', 'updated_at' => '2025-09-30 19:50:01'],
            ['id' => 27, 'division_id' => 3, 'last_name' => 'CATINOY', 'first_name' => 'JANET', 'middle_name' => 'TUNQUE', 'suffix' => null, 'position' => 'Engineer III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:50:36', 'updated_at' => '2025-09-30 19:50:36'],
            ['id' => 28, 'division_id' => 3, 'last_name' => 'CEPEDA', 'first_name' => 'CYRILL SHANE', 'middle_name' => 'TAGUIAM', 'suffix' => null, 'position' => 'Engineer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:51:44', 'updated_at' => '2025-09-30 19:51:44'],
            ['id' => 29, 'division_id' => 3, 'last_name' => 'JOSE', 'first_name' => 'DAN MARK', 'middle_name' => 'RILLERA', 'suffix' => null, 'position' => 'Engineer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:52:13', 'updated_at' => '2025-09-30 19:52:13'],
            ['id' => 30, 'division_id' => 3, 'last_name' => 'LANGCAY', 'first_name' => 'MICHAEL ANGELO', 'middle_name' => 'ROBLES', 'suffix' => null, 'position' => 'Engineer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:52:45', 'updated_at' => '2025-09-30 19:52:45'],
            ['id' => 31, 'division_id' => 3, 'last_name' => 'CASUGA', 'first_name' => 'RICA', 'middle_name' => 'VALENTINO', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:53:15', 'updated_at' => '2025-09-30 19:53:15'],
            ['id' => 32, 'division_id' => 3, 'last_name' => 'GUIMMAYEN', 'first_name' => 'NEIL KRISTOPHER', 'middle_name' => 'CONEL', 'suffix' => null, 'position' => 'Engineer II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:53:52', 'updated_at' => '2025-09-30 19:53:52'],
            ['id' => 33, 'division_id' => 3, 'last_name' => 'JIMENEZ', 'first_name' => 'ROEL', 'middle_name' => 'URSUA', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:55:30', 'updated_at' => '2025-09-30 19:55:30'],
            ['id' => 34, 'division_id' => 3, 'last_name' => 'SUYU', 'first_name' => 'KYLE RUZZEL', 'middle_name' => 'CARONAN', 'suffix' => null, 'position' => 'PLO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:56:06', 'updated_at' => '2025-09-30 19:56:06'],
            ['id' => 35, 'division_id' => 3, 'last_name' => 'BANAN', 'first_name' => 'RICO', 'middle_name' => 'GUMARANG', 'suffix' => null, 'position' => 'PLO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:56:33', 'updated_at' => '2025-09-30 19:56:33'],
            ['id' => 36, 'division_id' => 3, 'last_name' => 'DAWIDEO', 'first_name' => 'SAMANTHA', 'middle_name' => 'PAYUKET', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:57:17', 'updated_at' => '2025-09-30 19:57:17'],
            ['id' => 37, 'division_id' => 3, 'last_name' => 'MENDOZA', 'first_name' => 'CZYIONE DAYL', 'middle_name' => 'ASUNCION', 'suffix' => null, 'position' => 'Engineer I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:57:41', 'updated_at' => '2025-09-30 19:57:41'],
            ['id' => 38, 'division_id' => 3, 'last_name' => 'CALDEZ', 'first_name' => 'CHRISTIAN LAZARO', 'middle_name' => 'FLORES', 'suffix' => null, 'position' => 'PDO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:58:23', 'updated_at' => '2025-09-30 19:58:23'],
            ['id' => 39, 'division_id' => 3, 'last_name' => 'JIMENEZ', 'first_name' => 'JEI ARISTON', 'middle_name' => 'CASTILLO', 'suffix' => null, 'position' => 'PLO 1', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:58:50', 'updated_at' => '2025-09-30 19:58:50'],
            ['id' => 40, 'division_id' => 3, 'last_name' => 'NUVAL', 'first_name' => 'VLADIMIR VIKTOR', 'middle_name' => 'GACUTAN', 'suffix' => null, 'position' => 'PMO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 19:59:39', 'updated_at' => '2025-09-30 19:59:39'],
            ['id' => 41, 'division_id' => 3, 'last_name' => 'URDILLAS', 'first_name' => 'JOYCE ANN', 'middle_name' => 'PADER', 'suffix' => null, 'position' => 'PDO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:00:07', 'updated_at' => '2025-09-30 20:00:07'],
            ['id' => 42, 'division_id' => 3, 'last_name' => 'LIM', 'first_name' => 'NARDO', 'middle_name' => 'ABARRA', 'suffix' => null, 'position' => 'Admin Aide IV/Driver II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:00:36', 'updated_at' => '2025-09-30 20:00:36'],
            ['id' => 43, 'division_id' => 3, 'last_name' => 'DECAPIA', 'first_name' => 'MARIO', 'middle_name' => 'ANTONIO', 'suffix' => 'JR', 'position' => 'Admin Aide IV', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:01:22', 'updated_at' => '2025-09-30 20:01:22'],
            ['id' => 44, 'division_id' => 3, 'last_name' => 'MARTIN', 'first_name' => 'GLENARD', 'middle_name' => 'FERNANDO', 'suffix' => null, 'position' => 'Engineer I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:01:53', 'updated_at' => '2025-09-30 20:01:53'],
            ['id' => 45, 'division_id' => 3, 'last_name' => 'GUIM', 'first_name' => 'ARIES ANTHONY', 'middle_name' => 'FUGGAY', 'suffix' => null, 'position' => 'Computer Maintenance Technologist II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:02:24', 'updated_at' => '2025-09-30 20:03:37'],
            ['id' => 46, 'division_id' => 3, 'last_name' => 'AGUDA', 'first_name' => 'CHRISTIAN DALE', 'middle_name' => 'COSTALES', 'suffix' => null, 'position' => 'PDO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:05:07', 'updated_at' => '2025-09-30 20:05:07'],
            ['id' => 47, 'division_id' => 4, 'last_name' => 'BARIUAN', 'first_name' => 'RONALD', 'middle_name' => 'SIUAGAN', 'suffix' => null, 'position' => 'ITO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:41:11', 'updated_at' => '2025-09-30 20:41:11'],
            ['id' => 48, 'division_id' => 4, 'last_name' => 'HUBALDE', 'first_name' => 'ROLAND', 'middle_name' => 'BARTILAD', 'suffix' => null, 'position' => 'ECET I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:42:17', 'updated_at' => '2025-09-30 20:42:17'],
            ['id' => 49, 'division_id' => 4, 'last_name' => 'CANO', 'first_name' => 'ADELMO', 'middle_name' => 'GATO', 'suffix' => null, 'position' => 'CEO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:43:28', 'updated_at' => '2025-09-30 20:43:28'],
            ['id' => 50, 'division_id' => 4, 'last_name' => 'GALOLO', 'first_name' => 'LEAH', 'middle_name' => 'GALAROSSA', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:43:57', 'updated_at' => '2025-09-30 20:43:57'],
            ['id' => 51, 'division_id' => 4, 'last_name' => 'ABBAS', 'first_name' => 'ALISON AHMAD', 'middle_name' => 'LLAUDERES', 'suffix' => null, 'position' => 'PDO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:44:38', 'updated_at' => '2025-09-30 20:44:38'],
            ['id' => 52, 'division_id' => 4, 'last_name' => 'NATIVIDAD', 'first_name' => 'HERLYN KAYE', 'middle_name' => 'CALDITO', 'suffix' => null, 'position' => 'PDO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:45:23', 'updated_at' => '2025-09-30 20:45:23'],
            ['id' => 53, 'division_id' => 5, 'last_name' => 'LAYUGAN', 'first_name' => 'ROGELIO', 'middle_name' => 'TAGUIBAO', 'suffix' => null, 'position' => 'ITO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:45:57', 'updated_at' => '2025-09-30 20:45:57'],
            ['id' => 54, 'division_id' => 5, 'last_name' => 'ABAD', 'first_name' => 'FERDINAND', 'middle_name' => 'BARIUAN', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:46:35', 'updated_at' => '2025-09-30 20:46:35'],
            ['id' => 55, 'division_id' => 5, 'last_name' => 'BALIGOD', 'first_name' => 'RICHARD', 'middle_name' => 'PINEDA', 'suffix' => null, 'position' => 'ECET I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:47:12', 'updated_at' => '2025-09-30 20:47:12'],
            ['id' => 56, 'division_id' => 5, 'last_name' => 'BERMEJO', 'first_name' => 'ALVIN', 'middle_name' => 'BALIGOD', 'suffix' => null, 'position' => 'ECET I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:47:53', 'updated_at' => '2025-09-30 20:47:53'],
            ['id' => 57, 'division_id' => 5, 'last_name' => 'PECSON', 'first_name' => 'MARICAR', 'middle_name' => 'SORIANO', 'suffix' => null, 'position' => 'ISA III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:48:23', 'updated_at' => '2025-09-30 20:48:23'],
            ['id' => 58, 'division_id' => 5, 'last_name' => 'RECOLIZADO', 'first_name' => 'JAYMAR', 'middle_name' => 'CORSINO', 'suffix' => null, 'position' => 'ISA III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:49:02', 'updated_at' => '2025-09-30 20:49:02'],
            ['id' => 59, 'division_id' => 5, 'last_name' => 'ANAPI', 'first_name' => 'DEEJAY', 'middle_name' => 'GATAN', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:49:37', 'updated_at' => '2025-09-30 20:49:37'],
            ['id' => 60, 'division_id' => 5, 'last_name' => 'RAFER', 'first_name' => 'YANCEE KEARVIN KYLE', 'middle_name' => 'AQUINO', 'suffix' => null, 'position' => 'PLO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:50:25', 'updated_at' => '2025-09-30 20:50:25'],
            ['id' => 61, 'division_id' => 5, 'last_name' => 'CAPILI', 'first_name' => 'CHRISTOPHER ELEESON', 'middle_name' => 'LARGADO', 'suffix' => null, 'position' => 'PDO 1', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:51:07', 'updated_at' => '2025-09-30 20:51:07'],
            ['id' => 62, 'division_id' => 5, 'last_name' => 'SEGURITAN', 'first_name' => 'DARLENE JOY', 'middle_name' => 'BASSIG', 'suffix' => null, 'position' => 'PDO 1', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:51:48', 'updated_at' => '2025-09-30 20:51:48'],
            ['id' => 63, 'division_id' => 5, 'last_name' => 'MAGGAY', 'first_name' => 'MAYLANIE', 'middle_name' => 'ORDOÑO', 'suffix' => null, 'position' => 'PLA', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:52:19', 'updated_at' => '2025-09-30 20:52:19'],
            ['id' => 64, 'division_id' => 6, 'last_name' => 'GAZZINGAN', 'first_name' => 'CIRILO', 'middle_name' => 'NACINO', 'suffix' => 'JR.', 'position' => 'ITO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:53:14', 'updated_at' => '2025-09-30 20:53:14'],
            ['id' => 65, 'division_id' => 6, 'last_name' => 'PABRO', 'first_name' => 'EUGENE', 'middle_name' => 'LOMPERO', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:53:53', 'updated_at' => '2025-09-30 20:53:53'],
            ['id' => 66, 'division_id' => 6, 'last_name' => 'NAZARITA', 'first_name' => 'CONCEPCION', 'middle_name' => 'CABALONGA', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:54:43', 'updated_at' => '2025-09-30 20:54:43'],
            ['id' => 67, 'division_id' => 6, 'last_name' => 'RAMIREZ', 'first_name' => 'DANIEL', 'middle_name' => 'PADILLA', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:55:17', 'updated_at' => '2025-09-30 20:55:17'],
            ['id' => 68, 'division_id' => 6, 'last_name' => 'ROBLES', 'first_name' => 'MARILYN', 'middle_name' => 'FLORES', 'suffix' => null, 'position' => 'CEO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:56:06', 'updated_at' => '2025-09-30 20:56:06'],
            ['id' => 69, 'division_id' => 6, 'last_name' => 'TOMAS', 'first_name' => 'BRYAN', 'middle_name' => 'HIDALGO', 'suffix' => null, 'position' => 'ISA II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:56:48', 'updated_at' => '2025-09-30 20:58:08'],
            ['id' => 70, 'division_id' => 6, 'last_name' => 'ALILAM', 'first_name' => 'LEO JAY', 'middle_name' => 'LORENZO', 'suffix' => null, 'position' => 'PLO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:57:42', 'updated_at' => '2025-09-30 20:57:42'],
            ['id' => 71, 'division_id' => 7, 'last_name' => 'CABACUNGAN', 'first_name' => 'LANIE', 'middle_name' => 'AGTARAP', 'suffix' => null, 'position' => 'CEO III', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:59:05', 'updated_at' => '2025-09-30 20:59:05'],
            ['id' => 72, 'division_id' => 7, 'last_name' => 'ABAD', 'first_name' => 'DIETHER', 'middle_name' => 'ALBANO', 'suffix' => null, 'position' => 'ISA I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 20:59:39', 'updated_at' => '2025-09-30 20:59:39'],
            ['id' => 73, 'division_id' => 7, 'last_name' => 'VALDEZ', 'first_name' => 'MARIA KRISTINE', 'middle_name' => 'TAGUINOD', 'suffix' => null, 'position' => 'PDO II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:00:15', 'updated_at' => '2025-09-30 21:00:15'],
            ['id' => 74, 'division_id' => 7, 'last_name' => 'GUILLERMO', 'first_name' => 'MARC IVAN', 'middle_name' => 'DIZON', 'suffix' => null, 'position' => 'PDO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:00:58', 'updated_at' => '2025-09-30 21:00:58'],
            ['id' => 75, 'division_id' => 8, 'last_name' => 'AGAOID', 'first_name' => 'EDISON', 'middle_name' => 'SALVADOR', 'suffix' => null, 'position' => 'ISA I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:02:25', 'updated_at' => '2025-09-30 21:02:25'],
            ['id' => 76, 'division_id' => 8, 'last_name' => 'CABACUNGAN', 'first_name' => 'MEDY JOSE', 'middle_name' => 'MOSADAS', 'suffix' => null, 'position' => 'MPO II (QUIRINO/SANTIAGO)', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:03:18', 'updated_at' => '2025-09-30 21:03:18'],
            ['id' => 77, 'division_id' => 8, 'last_name' => 'GARCIA', 'first_name' => 'JEANNE SHANNON', 'middle_name' => 'ORIAL', 'suffix' => null, 'position' => 'PDO 2', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:04:26', 'updated_at' => '2025-09-30 21:04:26'],
            ['id' => 78, 'division_id' => 8, 'last_name' => 'CLARO', 'first_name' => 'EXEN', 'middle_name' => 'BANTIYAN', 'suffix' => null, 'position' => 'PLA', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:04:58', 'updated_at' => '2025-09-30 21:04:58'],
            ['id' => 79, 'division_id' => 9, 'last_name' => 'ROSAL', 'first_name' => 'JOSEPH', 'middle_name' => null, 'suffix' => null, 'position' => 'ECET I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:05:37', 'updated_at' => '2025-09-30 21:05:37'],
            ['id' => 80, 'division_id' => 9, 'last_name' => 'TULAUAN', 'first_name' => 'JOHANNA', 'middle_name' => 'FERIDO', 'suffix' => null, 'position' => 'ITO I', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:06:04', 'updated_at' => '2025-09-30 21:06:04'],
            ['id' => 81, 'division_id' => 9, 'last_name' => 'MADDELA', 'first_name' => 'KARL STEVEN', 'middle_name' => 'ADALEM', 'suffix' => null, 'position' => 'ISA II', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:06:35', 'updated_at' => '2025-09-30 21:06:35'],
            ['id' => 82, 'division_id' => 9, 'last_name' => 'BACKIAWAN', 'first_name' => 'DEBORA', 'middle_name' => 'PIDO', 'suffix' => null, 'position' => 'PDO 1', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:07:11', 'updated_at' => '2025-09-30 21:07:11'],
            ['id' => 83, 'division_id' => 9, 'last_name' => 'USMAN', 'first_name' => 'MOHAMADNOR', 'middle_name' => 'GURO', 'suffix' => null, 'position' => 'PDO 1', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:07:44', 'updated_at' => '2025-09-30 21:07:44'],
            ['id' => 84, 'division_id' => 9, 'last_name' => 'PILOTIN', 'first_name' => 'MA. ELIJAH', 'middle_name' => 'HUGO', 'suffix' => null, 'position' => 'PLA', 'birth_date' => null, 'age' => null, 'gender' => null, 'place_of_birth' => null, 'address' => null, 'religion' => null, 'phone' => null, 'active' => 1, 'created_at' => '2025-09-30 21:08:22', 'updated_at' => '2025-09-30 21:08:22'],
        ];

        DB::table('employees')->insert($employees);
    }
}